CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE USUARIOS(
    IdUsuario SERIAL PRIMARY KEY,
    Correo VARCHAR(60) UNIQUE NOT NULL,
    Contrasenia VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE USUARIOSROLES (
    IdUsuarioRol SERIAL PRIMARY KEY,
	IdUsuario INT REFERENCES USUARIOS(IdUsuario) ON DELETE CASCADE,
    NombreCompleto VARCHAR(100) NOT NULL,
    Telefono BIGINT UNIQUE NOT NULL,
    Correo VARCHAR(60) UNIQUE NOT NULL,
    Contrasenia VARCHAR(255) NOT NULL,
	Rol VARCHAR(60) NOT NULL,
    Activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

SELECT*FROM USUARIOS;
SELECT*FROM USUARIOSROLES;